name: masjid
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2

  bloc: ^8.1.2
  dio: ^5.3.4
  get_it:
  equatable: ^2.0.5
  flutter_svg: null
  intl:
  animated_shimmer:

  hijri: ^3.0.0
  flutter_bloc: ^8.1.3
  flutter_screenutil: null


  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  get: 
  speech_to_text:
  share_plus: ^7.2.2


  hive:
  hive_flutter:
  path_provider:
  url_launcher: 
  dio_cache_interceptor: ^3.4.4
  dio_cache_interceptor_hive_store: ^3.2.1

  freezed_annotation: 

  flutter:
    sdk: flutter

  
 
  



dev_dependencies:
  flutter_native_splash:
  hive_generator: 
  build_runner: 
  freezed: 
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  json_serializable: null


flutter_native_splash:
  color: "#ffffff" # white
  image: assets/images/appicon.png
  android: true
  ios: true
  android_12:
    image: assets/images/appicon.png
    icon_background_color: "#CC4022"
 


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
    - family: QueenFont
      fonts:
        - asset: assets/fonts/QueensVarTrial.ttf

    - family: QueenFontBold
      fonts:
        - asset: assets/fonts/QueensCondensedTrial-ExtraBold.ttf
